### ISSUE TITLE
'mono' could not be spawned

### ISSUE THREAD

**Issue by jonschoning** [ionide/ionide-fsharp#128]
![-home-jon-fs-git-pluckdatadownloader - atom_015](https://cloud.githubusercontent.com/assets/137183/9974456/a407ce90-5e55-11e5-9dd5-dae75670810d.png)

![image](https://cloud.githubusercontent.com/assets/137183/9974457/bde511b0-5e55-11e5-93a9-9f29592435bf.png)

**Comment by Krzysztof-Cieslak** [comment]
In ionide-fsharp plugin settings there is place to give path to mono, try to setting it up.

**Comment by ChrisNikkel** [comment]
Running into the same issue on Yosemite and setting it up to the explicit path (both in /usr/bin and directly to /Library/Frameworks/Mono.framework/Commands/mono) did not solve the issue.  

whereis mono
/usr/bin/mono

Jan 21  2013 /usr/bin/mono -> /Library/Frameworks/Mono.framework/Commands/mono

**Comment by Krzysztof-Cieslak** [comment]
Hey, can You try upgrading to `ionide-fsharp` 1.0.7. Should be fixed

**Comment by stweb** [comment]
hmm, just updated, set path to /usr/local/bin/

**Comment by jonschoning** [comment]
fixed with ionide-installer 1.2.1

**Comment by stweb** [comment]
hmm, seems to be back with 1.2.2, my path is configure to /usr/local/bin where mono

**Comment by peterson** [comment]
Having the same issue here (using ionide-fsharp 1.3.1 currently). I have tried this with many versions of ionide-fsharp (and earlier, atom-fsharp) without success. 

I have installed mono using homebrew. "mono" sits in /usr/local/bin/mono (actually a symlink to /usr/local/Cellar/mono/<version>/bin/mono). I've tried the following for MonoPath setting: "/usr/local/bin", "/usr/local/bin/mono", "mono". None of these work; spawn error every time.

Does anyone have a working atom configuration based on OSX 10.10 and fsharp and mono installed via homebrew? Suggest this ticket be reopened or another one created.

**Comment by ChrisNikkel** [comment]
![k2r4_3bk9tqkwhmyif1_a543w9c8rbx06ejikrieffm](https://cloud.githubusercontent.com/assets/1404474/10186403/919a34ec-6705-11e5-8f78-a4da050f48a1.png)

I am still getting an error, however it does seem to work even though the error appears.

**Comment by palutz** [comment]
same problem here... tried all the things proposed but still not working.

**Comment by sebfia** [comment]
Same here! This error occurs since I upgraded to El Capitan...

**Comment by LimoWanKenobi** [comment]
After updating my Mac to OSX 10.11 El Capitan, I got the same error.
I read in a [StackOverflow answer](http://stackoverflow.com/a/32547884) the following:

> Newer versions of mono comply to the "El Capitan" requirements of not installing anything into /usr/bin and thus now /usr/local/bin is used. I am not sure which mono 4.x release that started in...

Correct configuration in OSX
-------------------------------
Mono Path
`/usr/local/bin`
![fsharp formatting - atom 2015-10-04 18-45-17](https://cloud.githubusercontent.com/assets/403823/10268947/11995ab8-6ac8-11e5-9a4c-c5505d755f19.png)

Incorrect configuration in OSX
-------------------------------
Configuring the Mono Path to `/usr/local/bin/mono`
![fsharp formatting - atom 2015-10-04 18-42-35](https://cloud.githubusercontent.com/assets/403823/10268933/bf423e56-6ac7-11e5-8cdd-25a6a2cb5fd0.png)

Produces 
![fsharp formatting - atom 2015-10-04 18-43-35](https://cloud.githubusercontent.com/assets/403823/10268937/d61c87d0-6ac7-11e5-8715-a2904a7eee1f.png)

Error: spawn ENOTDIR
    at exports._errnoException (util.js:814:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:343:9)
    at Process__spawnSimple$ (/Users/edhzsz/.atom/packages/ionide-fsharp/lib/fsharp.js:3390:29)
    at LanguageService__start$ (/Users/edhzsz/.atom/packages/ionide-fsharp/lib/fsharp.js:2291:17)
    at FSharpIDE__activate$ (/Users/edhzsz/.atom/packages/ionide-fsharp/lib/fsharp.js:1579:5)
    at /Users/edhzsz/.atom/packages/ionide-fsharp/lib/fsharp.js:5088:14
    at Object.module.exports.IonideFSharp.activate (/Users/edhzsz/.atom/packages/ionide-fsharp/lib/fsharp.js:5111:26)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:245:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:226:30

**Comment by sebfia** [comment]
Still not working for me with above config. Which version of mono do you use?

**Comment by jimmydburr** [comment]
If you are having problems on OS X El Capitan see [#155](https://github.com/ionide/ionide-fsharp/issues/155). The problem concerns El Capitan's system protection of the $PATH variable for apps. Try running 'atom' from the terminal. If your errors do not appear, then you are seeing the El Capitan bug.

**Comment by lilred** [comment]
Yosemite here: same issue.

**Comment by Krzysztof-Cieslak** [comment]
Can you try updating all `ionide` packages and make sure that correct mono path is also set in `ionide-paket` plugin?

**Comment by peterson** [comment]
Fixed :)

I updated all packages, and also set the mono path within ionide-paket
settings as suggested and everything appears to be working now. Thanks for
your help!


On Thu, Oct 8, 2015 at 8:56 AM, Krzysztof Cieślak <notifications@github.com>
wrote:

> Can you try updating all ionide packages and make sure that correct mono
> path is also set in ionide-paket plugin?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ionide/ionide-fsharp/issues/128#issuecomment-146344494>
> .
>



-- 
David Peterson
Skype: davidhpeterson | Mobile: +61 415 943 940

**Comment by jimmydburr** [comment]
Yep, I confirm the fix. Working 100% now. Simply applying the updates and insuring the path was set correctly now does the trick.

Many thanks!!

**Comment by peterson** [comment]
@jimmydburr I'm on Yosemite (10.10.5) and it works for me.

**Comment by ChrisNikkel** [comment]
![screen shot 2015-10-08 at 8 46 04 pm](https://cloud.githubusercontent.com/assets/1404474/10385424/a884984c-6dfd-11e5-8d6b-318aae7ff5d9.png)

I uninstalled and reinstalled and set the path to mono to /usr/local/bin for both iodide-fsharp and ionide-paket and I am still having the issue.

**Comment by jimmydburr** [comment]
@ChrisNikkel note that El Capitan changes ownership of /usr/local files and this could be an issue for you? You may want to chown -R your-user-name /usr/local

**Comment by ChrisNikkel** [comment]
![screenshot 2015-10-08 10 11 02](https://cloud.githubusercontent.com/assets/1404474/10411542/66cc3302-6f1e-11e5-8c2c-1784b26772c8.png)

Unfortunately that did not resolve the issue.

**Comment by ChrisNikkel** [comment]
![screen shot 2015-10-10 at 7 13 00 am](https://cloud.githubusercontent.com/assets/1404474/10411545/8278c318-6f1e-11e5-9440-a35baa100394.png)

Unfortunately that did not resolve the issue.

**Comment by lilred** [comment]
Can we reopen this issue?

**Comment by palutz** [comment]
Still problem here..
Updated, nothing changed.
Removed and reinstalled same issue. Not fixed here. :(

**Comment by rocklau** [comment]
Hi everyone! two places need to be changed.  Mono Path is in  ionide-paket and ionide-fsharp.  correct path is "/usr/local/bin" . I fixed my own issue.

**Comment by halcwb** [comment]
Changed paths for fsharp and paket to usr/local/bin. Did a chown -R. Started Atom from terminal. Nothing works, keep getting the mono could not be spawned error. I have the latest versions, did an update just now, no result.

**Comment by iskeld** [comment]
There are few possible issues here - I got rid of "mono could not be spawned" after setting correct paths in the ionide-* package properies. However after opening FSI panel I get the following error:

/usr/local/bin/fsharpi: line 24: exec: mono: not found

That's another issue... First of all, after updating to El Capitan my mono installation got removed and I had to reinstall it. After reinstalling it was installed to /usr/local/bin (new behavior on El Capitan). Unfortunately GUI application under OSX don't have /usr/local/bin in their PATH (you can verify this by checking out process.env["PATH"] in Atom developer's tools console). I was unable to fix this and this is a bigger issue affecting many packages: https://github.com/atom/atom/issues/6956

**Comment by iskeld** [comment]
I managed to fix it temporarily by running 
sudo launchctl config user path /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by usr** [comment]
I got rid of this error message by doing the following: 

Currently I use:
* OSX version 10.11.1
* Atom version 1.0.19
* mono version 4.2.0 (Stable 4.2.0.179/a224653 Fri Aug 28 13:53:46 PDT 2015) installed using brew
* ionide-paket version 2.2.0
* ionide-fsharp version 1.4.0
* uninstalled the atom-fsharp package

Go to Settings > Packages 
In the settings of *both* the ionide-paket and ionide-fsharp packages set the Mono Path to: /usr/local/bin
Restart Atom

**Comment by OlegZee** [comment]
The same here: OSX 10.11.1, updated both paths and it works fine. Thanks ppl for good advice.

**Comment by haf** [comment]
Would it be possible to have it just look it up under my PATH?

**Comment by Krzysztof-Cieslak** [comment]
@haf, unfortunately, there is known bug in Atom which makes instance not having access to PATH in some cases.

**Comment by carsten-j** [comment]
I still get this error. I am running ionide-fsharp 1.4.11, Atom 1.2.4, and OSX 10.11.1

**Comment by ygrenzinger** [comment]
I have tried multiple time without success too :( Keeps 'could not be spawned'

**Comment by zellus** [comment]
Unable to spawn mono ... ionide-fsharp 1.4.12, Atom 1.2.4, and OSX 10.11.1

**Comment by rstradling** [comment]
OSX 10.11.1
Atom 1.3.1
ionide-fsharp 1.5.0
brew install of mono

# Proving mono works 
vim-fsharp ryanstradling$ mono --version
Mono JIT compiler version 4.2.0 (Stable 4.2.0.179/a224653 Fri Aug 28 13:53:46 PDT 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

vim-fsharp ryanstradling$ atom
First time got an error that it could not spawn /usr/local/bin/mono
Second time same thing...
Third time no longer see the error.

I realize this seems very odd but had this behavior also when setting the path properly for fsi

**Comment by eiriktsarpalis** [comment]
Confirming that I'm experiencing the same issue with OSX 10.11.2, Atom 1.3.1 and Ionide 1.5.0. None of the suggested workarounds have worked for me.

**Comment by rgiaccio** [comment]
Can this issue be reopened? I am having the same exact problem here with OSX 10.11.2, mono 4.2.1, Atom 1.3.2, ionide-fsharp 1.5.0, ionide-fsi 1.0.9, ionide-installer 1.3.0, ionide-paket 2.2.3, so everything with the latest version.

- mono is installed in /usr/local/bin
- in the ionide-fsharp and ionide-paket configs the parameter "Mono Path" are set to /usr/local/bin
- in the ionide-fsi config the parameter "Fsi Path" is set to fsharpi

When Atom starts a red error alert pops out saying:

    '/usr/local/bin/mono' could not be spawned. Is it
    installed and on your path? If so please open an issue
    on the package spawning the process.

![screenshot](https://cloud.githubusercontent.com/assets/1587116/11912464/c058bab6-a63d-11e5-9d7d-a40af8f56cdd.jpg)

If I try to start fsi another error alert comes out:

    'fsharpi' could not be spawned. Is it
    installed and on your path? If so please open an issue
    on the package spawning the process.

If in ionide-fsi I replace "fsharpi" with "/usr/local/bin/fsharpi" I still have an alert saying:

    '/usr/local/bin/fsharpi' could not be spawned. Is it
    installed and on your path? If so please open an issue on
    the package spawning the process.

All of this starting Atom both with a double click and from the terminal, where the PATH variable contains /usr/local/bin and I can start any mono command without any problem.

**Comment by SabotageAndi** [comment]
I have the same problem as @rgiaccio  and @eiriktsarpalis. 
When I start the FsAutoComplete.Suave.exe on my own, it is working.

Is there a possibility to get more debug information?

**Comment by SabotageAndi** [comment]
Using the mono package from http://www.mono-project.com/download/ is working.
Before that, I used the version from Homebrew.

**Comment by AlexSugak** [comment]
Having the same issue - "'/usr/bin/mono' could not be spawned".
OSX 10.8.5
Mono 4.2.1 at /usr/bin/mono   (installed from http://www.mono-project.com/download/)
Atom 1.3.2
ionide-fsharp 1.5.0
ionide-packet 2.2.3

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `1.6.0` for `Ionide-fsharp` and `2.2.5` for `Ionide-Paket`

**Comment by ctaggart** [comment]
I just installed `1.7.0` on my Mac and it works after setting the path to `/usr/bin/local`. It would be great if looked for mono there by default.

**Comment by vladkosarev** [comment]
Same issue here with El Capitan, changing to /usr/local/bin did the trick

**Comment by alanrsoares** [comment]
1.8.1 running on OSX El Capitan, same problem here.
Changing the path to `/usr/local/bin` `DOES NOT` solve the problem!

**Comment by takemyoxygen** [comment]
Same problem on OS X 10.11.4.
After I change path to mono to `/usr/local/bin` for *both* `ionide-fsharp` and `ionide-paket` this error stopped appearing, but on each `FAKE: Build` now I get
```
FAKE Error:
/path/to/build.sh: line 21: mono: command not found
```

**Comment by dkandalov** [comment]
Same problem on OS X 10.11.5
ionide-fsharp 1.9.1

**Comment by halcwb** [comment]
Sorry, but can't believe this still is an issue. Did a fresh download of Atom and Ionide installer and immediately got the dreaded Uncaught Error: spawn usr/local/bin/mono ENOENT. The path is set to usr/local/bin. There definitely is a mono there.

I run OS X 10.11.15. I have also, Xamarin installed. 

And then I entered `/usr/local/bin` instead of the standard `usr/local/bin` which fixed the issue.

**Comment by joncooper** [comment]
Same issue. I keep my packages in `/opt/boxen/homebrew/` and am trying to reference at `/opt/boxen/homebrew/bin/mono`

**Comment by GarethOates** [comment]
Fresh install of ionide-fsharp plugin today (using ionide-installer) and I'm also getting this issue.
![screen shot 2016-10-17 at 22 26 15](https://cloud.githubusercontent.com/assets/362627/19454303/e29df46e-94b8-11e6-8c3e-52431cbba0c3.png)

**Comment by teddevaal** [comment]
Same issue here unfortunate. Updating the path does not solve this issue.

**Comment by t0fuu** [comment]
same here i did as described and changed the path to /usr/local/bin and still get the error. same when starting from commandline.
